# Build the manager binary
# FROM registry.access.redhat.com/ubi8/go-toolset:1.17.7 as builder
FROM registry.access.redhat.com/ubi9/go-toolset:1.20 AS builder

USER root
WORKDIR /workspace
COPY . .
RUN make clean && make build

FROM registry.access.redhat.com/ubi9/ubi-minimal

LABEL MAINTAINER "Adrian Riobo" "<ariobolo@redhat.com>"

COPY --from=builder /workspace/out/qe-eventmanager /workspace/oci/entrypoint.sh /usr/local/bin/

ENTRYPOINT entrypoint.sh 
