---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: quay.io/ariobolo/qe-eventmanager:${VERSION}
        env:
        - name: PROVIDERS_FILE_PATH   
          value: /etc/eventmanager/providers.yaml
        - name: FLOWS_FILE_PATH   
          value: /etc/eventmanager/flow1.yaml,/etc/eventmanager/flow2.yaml
        volumeMounts:
        - name: providers 
          mountPath: /etc/eventmanager/providers.yaml
          subPath: providers.yaml
        - name: flows 
          mountPath: /etc/eventmanager/flow1.yaml
          subPath: flow1.yaml
        - name: flows 
          mountPath: /etc/eventmanager/flow2.yaml
          subPath: flow2.yaml
      serviceAccountName: eventmanager
      volumes:
      - name: providers
        secret:
          secretName: eventmanager-providers
      - name: flows
        configMap:
          name: eventmanager-flows
