---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eventmanager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: eventmanager
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eventmanager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: eventmanager
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["tasks", "taskruns", "pipelines", "pipelineruns", "pipelineresources", "conditions"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eventmanager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: eventmanager
subjects:
- kind: ServiceAccount
  name: eventmanager
roleRef:
  kind: Role 
  name: eventmanager
  apiGroup: rbac.authorization.k8s.io